# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task83d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task83d
  template:
    metadata:
      labels:
        app: task83d
    spec:
      containers:
      - name: book-catalog
        image: akshat23092024.azurecr.io/book_catalog:${VERSION}
        ports:
        - containerPort: 8081
      - name: inventory-management
        image: akshat23092024.azurecr.io/inventory_management:${VERSION}
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: task83d-service
spec:
  selector:
    app: task83d
  ports:
    - name: book-catalog-port
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: inventory-management-port
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
